name: ${PROJECT_NAME}
services:
  dockwater:
    build:
      dockerfile: Dockerfile.dockwater_humble
    image: dockwater:humble
  dev:
    depends_on:
      - dockwater
    build:
      context: .
      args:
        ROS_DIST: ${ROS_DIST}  # Default to 'humble' if not set
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_USER: ${PROJECT_USER}
        PROJECT_UID: ${PROJECT_UID}
        PROJECT_GID: ${PROJECT_GID}
        TARGET_ROS_WS: ${TARGET_ROS_WS}
    container_name: boatvdev
    image: "${PROJECT_NAME}_dev"
    stdin_open: true 
    tty: true  
    user: "${PROJECT_UID}:${PROJECT_GID}"
    command: /bin/bash
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///home/${PROJECT_USER}/${PROJECT_NAME}/cyclonedds.xml
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      - PROJECT_NAME=${PROJECT_NAME}
      - ROS_DIST=${ROS_DIST}
      - PROJECT_USER=${PROJECT_USER}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORMTHEME=qt5ct
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - TARGET_ROS_WS=${TARGET_ROS_WS}
      - LIBGL_ALWAYS_INDIRECT=1   # New: Allow indirect rendering
      - MESA_GL_VERSION_OVERRIDE=4.6  # New: Override GL version for compatibility
    volumes:
      - .:${TARGET_ROS_WS}
      - .vscode:/home/${PROJECT_USER}/.vscode-server
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/${PROJECT_USER}/.Xauthority
      - /dev/input:/dev/input
      - /dev/serial:/dev/serial
      - /dev/dri:/dev/dri
      - ~/.ssh:/home/${PROJECT_USER}/.ssh
      - .gz:/home/${PROJECT_USER}/.gz
    network_mode: host
    privileged: true
    ipc: host
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
