name: ${VERA_PROJECT_NAME}
services:
  # dockwater:
  #   build:
  #     dockerfile: Dockerfile.dockwater_${VERA_ROS_DIST}
  #   image: dockwater:${VERA_ROS_DIST}-latest

  dev:
    # depends_on:
      # - dockwater
    build:
      context: .
      args:
        VERA_ROS_DIST: ${VERA_ROS_DIST}
        VERA_PROJECT_NAME: ${VERA_PROJECT_NAME}
        VERA_DOCKER_USER: ${VERA_DOCKER_USER}
        VERA_DOCKER_UID: ${VERA_DOCKER_UID}
        VERA_DOCKER_GID: ${VERA_DOCKER_GID}
        VERA_DOCKER_DIR: ${VERA_DOCKER_DIR}
    container_name: ${VERA_PROJECT_NAME}_dev
    image: "${VERA_PROJECT_NAME}_dev:latest"
    stdin_open: true
    tty: true
    environment:
      - VERA_PROJECT_NAME=${VERA_PROJECT_NAME}
      - VERA_DOCKER_DIR=${VERA_DOCKER_DIR}
      - VERA_ROS_DIST=${VERA_ROS_DIST}
      - VERA_DOCKER_USER=${VERA_DOCKER_USER}
      - VERA_ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      #- ROS_LOCALHOST_ONLY=1
      #cyclone dds
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file://${VERA_DOCKER_DIR}/cyclonedds.xml
       #Nvidia display magic
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORMTHEME=qt5ct
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - LIBGL_ALWAYS_INDIRECT=1
      - MESA_GL_VERSION_OVERRIDE=4.6
    volumes:
      #main code
      - .:${VERA_DOCKER_DIR}
      #development chain persistent
      - ~/.ssh:/home/${VERA_DOCKER_USER}/.ssh #share keys with host
      #- .vscode:/home/${VERA_DOCKER_USER}/.vscode-server #vscode cache
      - .gz:/home/${VERA_DOCKER_USER}/.gz #gazebo worlds cache
      #hardware access
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/${VERA_DOCKER_USER}/.Xauthority
      - /dev/input:/dev/input
      - /dev/serial:/dev/serial
      - /dev/dri:/dev/dri  
      - /dev:/dev
    network_mode: host
    privileged: true
    ipc: host #for optional dds intercontainer communication
    runtime: nvidia
    gpus: all #some more Nvidia magic
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  ui:
    extends:
      service: dev
    command: /bin/bash -c " \
            source ${VERA_DOCKER_DIR}/scripts/setup.bash && \
            source ${VERA_DOCKER_DIR}/install/setup.bash && \
            ros2 launch vera_ui ${VERA_MODEL}.launch.py"
    container_name: ${VERA_PROJECT_NAME}_ui
  hw:
    extends:
      service: dev
    command: /bin/bash -c " \
            source ${VERA_DOCKER_DIR}/scripts/setup.bash && \
            source ${VERA_DOCKER_DIR}/install/setup.bash && \
            ros2 launch vera_hw ${VERA_MODEL}.launch.py"
    container_name: ${VERA_PROJECT_NAME}_hw
  core:
    extends:
      service: dev
    command: /bin/bash -c " \
            source ${VERA_DOCKER_DIR}/scripts/setup.bash && \
            source ${VERA_DOCKER_DIR}/install/setup.bash && \
            ros2 launch vera_core ${VERA_MODEL}.launch.py"
    container_name: ${VERA_PROJECT_NAME}_core

  
